export const EnvKeys = {
  PORT: 'PORT',
  FRONTEND_URL: 'FRONTEND_URL',
  DATABASE_URL: 'DATABASE_URL',
  POSTGRES_PORT: 'POSTGRES_PORT',
  POSTGRES_USER: 'POSTGRES_USER',
  POSTGRES_PASSWORD: 'POSTGRES_PASSWORD',
  POSTGRES_DB: 'POSTGRES_DB',
  API_JWT_SECRET: 'API_JWT_SECRET',
  TMDB_ACCESS_TOKEN: 'TMDB_ACCESS_TOKEN',
  TMDB_BASE_URL: 'TMDB_BASE_URL',
  CLAUDE_KEY: 'CLAUDE_KEY',
  CRON_SECRET: 'CRON_SECRET',
} as const;
