export const EnvKeys = {
  PORT: 'PORT',
  FRONTEND_URL: 'FRONTEND_URL',
  DATABASE_URL: 'DATABASE_URL',
  POSTGRES_PORT: 'POSTGRES_PORT',
  POSTGRES_USER: 'POSTGRES_USER',
  POSTGRES_PASSWORD: 'POSTGRES_PASSWORD',
  POSTGRES_DB: 'POSTGRES_DB',

  API_JWT_SECRET: 'API_JWT_SECRET',

  TMDB_ACCESS_TOKEN: 'TMDB_ACCESS_TOKEN',
  TMDB_BASE_URL: 'TMDB_BASE_URL',

  CLAUDE_KEY: 'CLAUDE_KEY',
  CLAUDE_MODEL: 'CLAUDE_MODEL',
  OPENAI_KEY: 'OPENAI_KEY',
  OPENAI_MODEL: 'OPENAI_MODEL',
  CRON_SECRET: 'CRON_SECRET',

  DEMO_SEED_ENABLED: 'DEMO_SEED_ENABLED',
  DEMO_SEED_SECRET: 'DEMO_SEED_SECRET',
  DEMO_SEED_PASSWORD: 'DEMO_SEED_PASSWORD',
  TEST_USER_EMAIL: 'TEST_USER_EMAIL',
  TEST_USER_PASSWORD: 'TEST_USER_PASSWORD',

  KAKAO_REST_API_KEY: 'KAKAO_REST_API_KEY',
  KAKAO_OAUTH_CLIENT_SECRET: 'KAKAO_OAUTH_CLIENT_SECRET',
  KAKAO_CALLBACK_URL: 'KAKAO_CALLBACK_URL',

  KOBIS_API_KEY: 'KOBIS_API_KEY',

  GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET: 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CALLBACK_URL: 'GOOGLE_CALLBACK_URL',

  NAVER_CLIENT_ID: 'NAVER_CLIENT_ID',
  NAVER_CLIENT_SECRET: 'NAVER_CLIENT_SECRET',
  NAVER_CALLBACK_URL: 'NAVER_CALLBACK_URL',

  APPLE_CLIENT_ID: 'APPLE_CLIENT_ID',
  APPLE_TEAM_ID: 'APPLE_TEAM_ID',
  APPLE_KEY_ID: 'APPLE_KEY_ID',
  APPLE_PRIVATE_KEY: 'APPLE_PRIVATE_KEY',
  APPLE_CALLBACK_URL: 'APPLE_CALLBACK_URL',
} as const;
